package pojo_classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Deceases generated by hbm2java
 */
public class Deceases implements java.io.Serializable {

	private Integer id;
	private Enumerations enumerations;
	private String name;
	private String symptoms;
	private Set deceaseTreatmentLinks = new HashSet(0);

	public Deceases() {
	}

	public Deceases(String name) {
		this.name = name;
	}

	public Deceases(Enumerations enumerations, String name, String symptoms,
			Set deceaseTreatmentLinks) {
		this.enumerations = enumerations;
		this.name = name;
		this.symptoms = symptoms;
		this.deceaseTreatmentLinks = deceaseTreatmentLinks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Enumerations getEnumerations() {
		return this.enumerations;
	}

	public void setEnumerations(Enumerations enumerations) {
		this.enumerations = enumerations;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSymptoms() {
		return this.symptoms;
	}

	public void setSymptoms(String symptoms) {
		this.symptoms = symptoms;
	}

	public Set getDeceaseTreatmentLinks() {
		return this.deceaseTreatmentLinks;
	}

	public void setDeceaseTreatmentLinks(Set deceaseTreatmentLinks) {
		this.deceaseTreatmentLinks = deceaseTreatmentLinks;
	}

}
