package pojo_classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

/**
 * DeceaseTreatmentLink generated by hbm2java
 */
public class DeceaseTreatmentLink implements java.io.Serializable {

	private Integer id;
	private Deceases deceases;
	private Treatments treatments;

	public DeceaseTreatmentLink() {
	}

	public DeceaseTreatmentLink(Deceases deceases, Treatments treatments) {
		this.deceases = deceases;
		this.treatments = treatments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Deceases getDeceases() {
		return this.deceases;
	}

	public void setDeceases(Deceases deceases) {
		this.deceases = deceases;
	}

	public Treatments getTreatments() {
		return this.treatments;
	}

	public void setTreatments(Treatments treatments) {
		this.treatments = treatments;
	}

}
