package pojo_classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EnumerationTypes generated by hbm2java
 */
public class EnumerationTypes implements java.io.Serializable {

	private String type;
	private String description;
	private Set enumerationses = new HashSet(0);

	public EnumerationTypes() {
	}

	public EnumerationTypes(String type) {
		this.type = type;
	}

	public EnumerationTypes(String type, String description, Set enumerationses) {
		this.type = type;
		this.description = description;
		this.enumerationses = enumerationses;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getEnumerationses() {
		return this.enumerationses;
	}

	public void setEnumerationses(Set enumerationses) {
		this.enumerationses = enumerationses;
	}

}
