package pojo_classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Medicaments generated by hbm2java
 */
public class Medicaments implements java.io.Serializable {

	private Integer id;
	private Enumerations enumerations;
	private String name;
	private String content;
	private String prescription;
	private String status;
	private Float price;
	private Set caseInfos = new HashSet(0);
	private Set treatmentMedicamentLinks = new HashSet(0);

	public Medicaments() {
	}

	public Medicaments(String name, String content, String status) {
		this.name = name;
		this.content = content;
		this.status = status;
	}

	public Medicaments(Enumerations enumerations, String name, String content,
			String prescription, String status, Float price, Set caseInfos,
			Set treatmentMedicamentLinks) {
		this.enumerations = enumerations;
		this.name = name;
		this.content = content;
		this.prescription = prescription;
		this.status = status;
		this.price = price;
		this.caseInfos = caseInfos;
		this.treatmentMedicamentLinks = treatmentMedicamentLinks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Enumerations getEnumerations() {
		return this.enumerations;
	}

	public void setEnumerations(Enumerations enumerations) {
		this.enumerations = enumerations;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPrescription() {
		return this.prescription;
	}

	public void setPrescription(String prescription) {
		this.prescription = prescription;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Set getCaseInfos() {
		return this.caseInfos;
	}

	public void setCaseInfos(Set caseInfos) {
		this.caseInfos = caseInfos;
	}

	public Set getTreatmentMedicamentLinks() {
		return this.treatmentMedicamentLinks;
	}

	public void setTreatmentMedicamentLinks(Set treatmentMedicamentLinks) {
		this.treatmentMedicamentLinks = treatmentMedicamentLinks;
	}

}
