package pojo_classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

/**
 * OrganizationContactLink generated by hbm2java
 */
public class OrganizationContactLink implements java.io.Serializable {

	private Integer id;
	private Organizations organizations;
	private Contacts contacts;

	public OrganizationContactLink() {
	}

	public OrganizationContactLink(Organizations organizations,
			Contacts contacts) {
		this.organizations = organizations;
		this.contacts = contacts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Organizations getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}

	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

}
