package pojo_classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persons generated by hbm2java
 */
public class Persons implements java.io.Serializable {

	private String socialNumber;
	private Enumerations enumerationsByJobTitle;
	private Enumerations enumerationsByTitle;
	private Enumerations enumerationsByRole;
	private Enumerations enumerationsBySex;
	private String firstName;
	private String middleName;
	private String lastName;
	private Date birthDate;
	private Set personOrganizationLinks = new HashSet(0);
	private Set medicalCaseses = new HashSet(0);
	private Set personContactLinks = new HashSet(0);
	private Set touristVisits = new HashSet(0);
	private Set caseInfos = new HashSet(0);

	public Persons() {
	}

	public Persons(String socialNumber, Enumerations enumerationsByJobTitle,
			Enumerations enumerationsByTitle, Enumerations enumerationsByRole,
			Enumerations enumerationsBySex, String firstName, String lastName,
			Date birthDate) {
		this.socialNumber = socialNumber;
		this.enumerationsByJobTitle = enumerationsByJobTitle;
		this.enumerationsByTitle = enumerationsByTitle;
		this.enumerationsByRole = enumerationsByRole;
		this.enumerationsBySex = enumerationsBySex;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDate = birthDate;
	}

	public Persons(String socialNumber, Enumerations enumerationsByJobTitle,
			Enumerations enumerationsByTitle, Enumerations enumerationsByRole,
			Enumerations enumerationsBySex, String firstName,
			String middleName, String lastName, Date birthDate,
			Set personOrganizationLinks, Set medicalCaseses,
			Set personContactLinks, Set touristVisits, Set caseInfos) {
		this.socialNumber = socialNumber;
		this.enumerationsByJobTitle = enumerationsByJobTitle;
		this.enumerationsByTitle = enumerationsByTitle;
		this.enumerationsByRole = enumerationsByRole;
		this.enumerationsBySex = enumerationsBySex;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.birthDate = birthDate;
		this.personOrganizationLinks = personOrganizationLinks;
		this.medicalCaseses = medicalCaseses;
		this.personContactLinks = personContactLinks;
		this.touristVisits = touristVisits;
		this.caseInfos = caseInfos;
	}

	public String getSocialNumber() {
		return this.socialNumber;
	}

	public void setSocialNumber(String socialNumber) {
		this.socialNumber = socialNumber;
	}

	public Enumerations getEnumerationsByJobTitle() {
		return this.enumerationsByJobTitle;
	}

	public void setEnumerationsByJobTitle(Enumerations enumerationsByJobTitle) {
		this.enumerationsByJobTitle = enumerationsByJobTitle;
	}

	public Enumerations getEnumerationsByTitle() {
		return this.enumerationsByTitle;
	}

	public void setEnumerationsByTitle(Enumerations enumerationsByTitle) {
		this.enumerationsByTitle = enumerationsByTitle;
	}

	public Enumerations getEnumerationsByRole() {
		return this.enumerationsByRole;
	}

	public void setEnumerationsByRole(Enumerations enumerationsByRole) {
		this.enumerationsByRole = enumerationsByRole;
	}

	public Enumerations getEnumerationsBySex() {
		return this.enumerationsBySex;
	}

	public void setEnumerationsBySex(Enumerations enumerationsBySex) {
		this.enumerationsBySex = enumerationsBySex;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Set getPersonOrganizationLinks() {
		return this.personOrganizationLinks;
	}

	public void setPersonOrganizationLinks(Set personOrganizationLinks) {
		this.personOrganizationLinks = personOrganizationLinks;
	}

	public Set getMedicalCaseses() {
		return this.medicalCaseses;
	}

	public void setMedicalCaseses(Set medicalCaseses) {
		this.medicalCaseses = medicalCaseses;
	}

	public Set getPersonContactLinks() {
		return this.personContactLinks;
	}

	public void setPersonContactLinks(Set personContactLinks) {
		this.personContactLinks = personContactLinks;
	}

	public Set getTouristVisits() {
		return this.touristVisits;
	}

	public void setTouristVisits(Set touristVisits) {
		this.touristVisits = touristVisits;
	}

	public Set getCaseInfos() {
		return this.caseInfos;
	}

	public void setCaseInfos(Set caseInfos) {
		this.caseInfos = caseInfos;
	}

}
