package pojo_classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Treatments generated by hbm2java
 */
public class Treatments implements java.io.Serializable {

	private Integer id;
	private Enumerations enumerations;
	private String name;
	private String description;
	private Float price;
	private Set treatmentMedicamentLinks = new HashSet(0);
	private Set deceaseTreatmentLinks = new HashSet(0);
	private Set caseInfos = new HashSet(0);

	public Treatments() {
	}

	public Treatments(String name) {
		this.name = name;
	}

	public Treatments(Enumerations enumerations, String name,
			String description, Float price, Set treatmentMedicamentLinks,
			Set deceaseTreatmentLinks, Set caseInfos) {
		this.enumerations = enumerations;
		this.name = name;
		this.description = description;
		this.price = price;
		this.treatmentMedicamentLinks = treatmentMedicamentLinks;
		this.deceaseTreatmentLinks = deceaseTreatmentLinks;
		this.caseInfos = caseInfos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Enumerations getEnumerations() {
		return this.enumerations;
	}

	public void setEnumerations(Enumerations enumerations) {
		this.enumerations = enumerations;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Set getTreatmentMedicamentLinks() {
		return this.treatmentMedicamentLinks;
	}

	public void setTreatmentMedicamentLinks(Set treatmentMedicamentLinks) {
		this.treatmentMedicamentLinks = treatmentMedicamentLinks;
	}

	public Set getDeceaseTreatmentLinks() {
		return this.deceaseTreatmentLinks;
	}

	public void setDeceaseTreatmentLinks(Set deceaseTreatmentLinks) {
		this.deceaseTreatmentLinks = deceaseTreatmentLinks;
	}

	public Set getCaseInfos() {
		return this.caseInfos;
	}

	public void setCaseInfos(Set caseInfos) {
		this.caseInfos = caseInfos;
	}

}
