package database.pojo;

// Generated May 19, 2015 11:06:30 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CaseInfo generated by hbm2java
 */
public class CaseInfo implements java.io.Serializable {

	private Integer id;
	private Users usersByCreatedBy;
	private Enumerations enumerationsByStatus2;
	private MedicalReport medicalReport;
	private Users usersByLastUpdateBy;
	private Persons personsByResponsiblePerson;
	private Persons personsByPatientInfo;
	private Policies policies;
	private Enumerations enumerationsByStatus1;
	private Date caseDate;
	private String referanceNumber1;
	private String referanceNumber2;
	private Float franchise;
	private Set<Services> serviceses = new HashSet<Services>(0);
	private Set<Documentation> documentations = new HashSet<Documentation>(0);
	private Set<Invoices> invoiceses = new HashSet<Invoices>(0);

	public CaseInfo() {
	}

	public CaseInfo(Persons personsByPatientInfo, Date caseDate,
			String referanceNumber1) {
		this.personsByPatientInfo = personsByPatientInfo;
		this.caseDate = caseDate;
		this.referanceNumber1 = referanceNumber1;
	}

	public CaseInfo(Users usersByCreatedBy, Enumerations enumerationsByStatus2,
			MedicalReport medicalReport, Users usersByLastUpdateBy,
			Persons personsByResponsiblePerson, Persons personsByPatientInfo,
			Policies policies, Enumerations enumerationsByStatus1,
			Date caseDate, String referanceNumber1, String referanceNumber2,
			Float franchise, Set<Services> serviceses,
			Set<Documentation> documentations, Set<Invoices> invoiceses) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.enumerationsByStatus2 = enumerationsByStatus2;
		this.medicalReport = medicalReport;
		this.usersByLastUpdateBy = usersByLastUpdateBy;
		this.personsByResponsiblePerson = personsByResponsiblePerson;
		this.personsByPatientInfo = personsByPatientInfo;
		this.policies = policies;
		this.enumerationsByStatus1 = enumerationsByStatus1;
		this.caseDate = caseDate;
		this.referanceNumber1 = referanceNumber1;
		this.referanceNumber2 = referanceNumber2;
		this.franchise = franchise;
		this.serviceses = serviceses;
		this.documentations = documentations;
		this.invoiceses = invoiceses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Enumerations getEnumerationsByStatus2() {
		return this.enumerationsByStatus2;
	}

	public void setEnumerationsByStatus2(Enumerations enumerationsByStatus2) {
		this.enumerationsByStatus2 = enumerationsByStatus2;
	}

	public MedicalReport getMedicalReport() {
		return this.medicalReport;
	}

	public void setMedicalReport(MedicalReport medicalReport) {
		this.medicalReport = medicalReport;
	}

	public Users getUsersByLastUpdateBy() {
		return this.usersByLastUpdateBy;
	}

	public void setUsersByLastUpdateBy(Users usersByLastUpdateBy) {
		this.usersByLastUpdateBy = usersByLastUpdateBy;
	}

	public Persons getPersonsByResponsiblePerson() {
		return this.personsByResponsiblePerson;
	}

	public void setPersonsByResponsiblePerson(Persons personsByResponsiblePerson) {
		this.personsByResponsiblePerson = personsByResponsiblePerson;
	}

	public Persons getPersonsByPatientInfo() {
		return this.personsByPatientInfo;
	}

	public void setPersonsByPatientInfo(Persons personsByPatientInfo) {
		this.personsByPatientInfo = personsByPatientInfo;
	}

	public Policies getPolicies() {
		return this.policies;
	}

	public void setPolicies(Policies policies) {
		this.policies = policies;
	}

	public Enumerations getEnumerationsByStatus1() {
		return this.enumerationsByStatus1;
	}

	public void setEnumerationsByStatus1(Enumerations enumerationsByStatus1) {
		this.enumerationsByStatus1 = enumerationsByStatus1;
	}

	public Date getCaseDate() {
		return this.caseDate;
	}

	public void setCaseDate(Date caseDate) {
		this.caseDate = caseDate;
	}

	public String getReferanceNumber1() {
		return this.referanceNumber1;
	}

	public void setReferanceNumber1(String referanceNumber1) {
		this.referanceNumber1 = referanceNumber1;
	}

	public String getReferanceNumber2() {
		return this.referanceNumber2;
	}

	public void setReferanceNumber2(String referanceNumber2) {
		this.referanceNumber2 = referanceNumber2;
	}

	public Float getFranchise() {
		return this.franchise;
	}

	public void setFranchise(Float franchise) {
		this.franchise = franchise;
	}

	public Set<Services> getServiceses() {
		return this.serviceses;
	}

	public void setServiceses(Set<Services> serviceses) {
		this.serviceses = serviceses;
	}

	public Set<Documentation> getDocumentations() {
		return this.documentations;
	}

	public void setDocumentations(Set<Documentation> documentations) {
		this.documentations = documentations;
	}

	public Set<Invoices> getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set<Invoices> invoiceses) {
		this.invoiceses = invoiceses;
	}

}
