package database.pojo;

// Generated Apr 29, 2015 9:23:50 PM by Hibernate Tools 4.0.0

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private String id;
	private String nameBg;
	private String nameEn;

	public Country() {
	}

	public Country(String id, String nameBg, String nameEn) {
		this.id = id;
		this.nameBg = nameBg;
		this.nameEn = nameEn;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNameBg() {
		return this.nameBg;
	}

	public void setNameBg(String nameBg) {
		this.nameBg = nameBg;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

}
