package database.pojo;

// Generated Apr 4, 2015 7:32:07 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Enumerations generated by hbm2java
 */
public class Enumerations implements java.io.Serializable {

	private String code;
	private EnumerationTypes enumerationTypes;
	private Set<Persons> personsesForTitle = new HashSet<Persons>(0);
	private Set<Contacts> contactsesForPrefered = new HashSet<Contacts>(0);
	private Set<CaseInfo> caseInfosForStatus2 = new HashSet<CaseInfo>(0);
	private Set<Persons> personsesForRole = new HashSet<Persons>(0);
	private Set<Persons> personsesForSex = new HashSet<Persons>(0);
	private Set<EnumerationLabels> enumerationLabelses = new HashSet<EnumerationLabels>(
			0);
	private Set<Contacts> contactsesForActive = new HashSet<Contacts>(0);
	private Set<Documentation> documentations = new HashSet<Documentation>(0);
	private Set<Organizations> organizationses = new HashSet<Organizations>(0);
	private Set<Persons> personsesForJobTitle = new HashSet<Persons>(0);
	private Set<Contacts> contactsesForType = new HashSet<Contacts>(0);
	private Set<Treatments> treatmentses = new HashSet<Treatments>(0);
	private Set<CaseInfo> caseInfosForStatus1 = new HashSet<CaseInfo>(0);
	private Set<Medicaments> medicamentses = new HashSet<Medicaments>(0);

	public Enumerations() {
	}

	public Enumerations(String code, EnumerationTypes enumerationTypes) {
		this.code = code;
		this.enumerationTypes = enumerationTypes;
	}

	public Enumerations(String code, EnumerationTypes enumerationTypes,
			Set<Persons> personsesForTitle,
			Set<Contacts> contactsesForPrefered,
			Set<CaseInfo> caseInfosForStatus2, Set<Persons> personsesForRole,
			Set<Persons> personsesForSex,
			Set<EnumerationLabels> enumerationLabelses,
			Set<Contacts> contactsesForActive,
			Set<Documentation> documentations,
			Set<Organizations> organizationses,
			Set<Persons> personsesForJobTitle, Set<Contacts> contactsesForType,
			Set<Treatments> treatmentses, Set<CaseInfo> caseInfosForStatus1,
			Set<Medicaments> medicamentses) {
		this.code = code;
		this.enumerationTypes = enumerationTypes;
		this.personsesForTitle = personsesForTitle;
		this.contactsesForPrefered = contactsesForPrefered;
		this.caseInfosForStatus2 = caseInfosForStatus2;
		this.personsesForRole = personsesForRole;
		this.personsesForSex = personsesForSex;
		this.enumerationLabelses = enumerationLabelses;
		this.contactsesForActive = contactsesForActive;
		this.documentations = documentations;
		this.organizationses = organizationses;
		this.personsesForJobTitle = personsesForJobTitle;
		this.contactsesForType = contactsesForType;
		this.treatmentses = treatmentses;
		this.caseInfosForStatus1 = caseInfosForStatus1;
		this.medicamentses = medicamentses;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public EnumerationTypes getEnumerationTypes() {
		return this.enumerationTypes;
	}

	public void setEnumerationTypes(EnumerationTypes enumerationTypes) {
		this.enumerationTypes = enumerationTypes;
	}

	public Set<Persons> getPersonsesForTitle() {
		return this.personsesForTitle;
	}

	public void setPersonsesForTitle(Set<Persons> personsesForTitle) {
		this.personsesForTitle = personsesForTitle;
	}

	public Set<Contacts> getContactsesForPrefered() {
		return this.contactsesForPrefered;
	}

	public void setContactsesForPrefered(Set<Contacts> contactsesForPrefered) {
		this.contactsesForPrefered = contactsesForPrefered;
	}

	public Set<CaseInfo> getCaseInfosForStatus2() {
		return this.caseInfosForStatus2;
	}

	public void setCaseInfosForStatus2(Set<CaseInfo> caseInfosForStatus2) {
		this.caseInfosForStatus2 = caseInfosForStatus2;
	}

	public Set<Persons> getPersonsesForRole() {
		return this.personsesForRole;
	}

	public void setPersonsesForRole(Set<Persons> personsesForRole) {
		this.personsesForRole = personsesForRole;
	}

	public Set<Persons> getPersonsesForSex() {
		return this.personsesForSex;
	}

	public void setPersonsesForSex(Set<Persons> personsesForSex) {
		this.personsesForSex = personsesForSex;
	}

	public Set<EnumerationLabels> getEnumerationLabelses() {
		return this.enumerationLabelses;
	}

	public void setEnumerationLabelses(
			Set<EnumerationLabels> enumerationLabelses) {
		this.enumerationLabelses = enumerationLabelses;
	}

	public Set<Contacts> getContactsesForActive() {
		return this.contactsesForActive;
	}

	public void setContactsesForActive(Set<Contacts> contactsesForActive) {
		this.contactsesForActive = contactsesForActive;
	}

	public Set<Documentation> getDocumentations() {
		return this.documentations;
	}

	public void setDocumentations(Set<Documentation> documentations) {
		this.documentations = documentations;
	}

	public Set<Organizations> getOrganizationses() {
		return this.organizationses;
	}

	public void setOrganizationses(Set<Organizations> organizationses) {
		this.organizationses = organizationses;
	}

	public Set<Persons> getPersonsesForJobTitle() {
		return this.personsesForJobTitle;
	}

	public void setPersonsesForJobTitle(Set<Persons> personsesForJobTitle) {
		this.personsesForJobTitle = personsesForJobTitle;
	}

	public Set<Contacts> getContactsesForType() {
		return this.contactsesForType;
	}

	public void setContactsesForType(Set<Contacts> contactsesForType) {
		this.contactsesForType = contactsesForType;
	}

	public Set<Treatments> getTreatmentses() {
		return this.treatmentses;
	}

	public void setTreatmentses(Set<Treatments> treatmentses) {
		this.treatmentses = treatmentses;
	}

	public Set<CaseInfo> getCaseInfosForStatus1() {
		return this.caseInfosForStatus1;
	}

	public void setCaseInfosForStatus1(Set<CaseInfo> caseInfosForStatus1) {
		this.caseInfosForStatus1 = caseInfosForStatus1;
	}

	public Set<Medicaments> getMedicamentses() {
		return this.medicamentses;
	}

	public void setMedicamentses(Set<Medicaments> medicamentses) {
		this.medicamentses = medicamentses;
	}

}
