package database.pojo;

// Generated Apr 29, 2015 9:23:50 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Invoices generated by hbm2java
 */
public class Invoices implements java.io.Serializable {

	private Integer id;
	private CaseInfo caseInfo;
	private Integer number;
	private Date date;
	private int invoicedBy;
	private int invoicedTo;
	private Float policyExcess;
	private float dueAmount;
	private String storagePath;

	public Invoices() {
	}

	public Invoices(CaseInfo caseInfo, Date date, int invoicedBy,
			int invoicedTo, float dueAmount) {
		this.caseInfo = caseInfo;
		this.date = date;
		this.invoicedBy = invoicedBy;
		this.invoicedTo = invoicedTo;
		this.dueAmount = dueAmount;
	}

	public Invoices(CaseInfo caseInfo, Integer number, Date date,
			int invoicedBy, int invoicedTo, Float policyExcess,
			float dueAmount, String storagePath) {
		this.caseInfo = caseInfo;
		this.number = number;
		this.date = date;
		this.invoicedBy = invoicedBy;
		this.invoicedTo = invoicedTo;
		this.policyExcess = policyExcess;
		this.dueAmount = dueAmount;
		this.storagePath = storagePath;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CaseInfo getCaseInfo() {
		return this.caseInfo;
	}

	public void setCaseInfo(CaseInfo caseInfo) {
		this.caseInfo = caseInfo;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getInvoicedBy() {
		return this.invoicedBy;
	}

	public void setInvoicedBy(int invoicedBy) {
		this.invoicedBy = invoicedBy;
	}

	public int getInvoicedTo() {
		return this.invoicedTo;
	}

	public void setInvoicedTo(int invoicedTo) {
		this.invoicedTo = invoicedTo;
	}

	public Float getPolicyExcess() {
		return this.policyExcess;
	}

	public void setPolicyExcess(Float policyExcess) {
		this.policyExcess = policyExcess;
	}

	public float getDueAmount() {
		return this.dueAmount;
	}

	public void setDueAmount(float dueAmount) {
		this.dueAmount = dueAmount;
	}

	public String getStoragePath() {
		return this.storagePath;
	}

	public void setStoragePath(String storagePath) {
		this.storagePath = storagePath;
	}

}
