package database.pojo;

// Generated Apr 29, 2015 9:23:50 PM by Hibernate Tools 4.0.0

/**
 * Medicaments generated by hbm2java
 */
public class Medicaments implements java.io.Serializable {

	private Integer id;
	private Enumerations enumerations;
	private String name;
	private String content;
	private String prescription;
	private String status;
	private Float price;

	public Medicaments() {
	}

	public Medicaments(String name, String prescription) {
		this.name = name;
		this.prescription = prescription;
	}

	public Medicaments(Enumerations enumerations, String name, String content,
			String prescription, String status, Float price) {
		this.enumerations = enumerations;
		this.name = name;
		this.content = content;
		this.prescription = prescription;
		this.status = status;
		this.price = price;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Enumerations getEnumerations() {
		return this.enumerations;
	}

	public void setEnumerations(Enumerations enumerations) {
		this.enumerations = enumerations;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPrescription() {
		return this.prescription;
	}

	public void setPrescription(String prescription) {
		this.prescription = prescription;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

}
