package database.pojo;

// Generated Apr 29, 2015 9:23:50 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Policies generated by hbm2java
 */
public class Policies implements java.io.Serializable {

	private String number;
	private Organizations organizationsByAssistanceCompany;
	private Organizations organizationsByInsuaranceCompany;
	private Date validFrom;
	private Date validTo;
	private Set<CaseInfo> caseInfos = new HashSet<CaseInfo>(0);

	public Policies() {
	}

	public Policies(String number,
			Organizations organizationsByAssistanceCompany,
			Organizations organizationsByInsuaranceCompany, Date validFrom,
			Date validTo) {
		this.number = number;
		this.organizationsByAssistanceCompany = organizationsByAssistanceCompany;
		this.organizationsByInsuaranceCompany = organizationsByInsuaranceCompany;
		this.validFrom = validFrom;
		this.validTo = validTo;
	}

	public Policies(String number,
			Organizations organizationsByAssistanceCompany,
			Organizations organizationsByInsuaranceCompany, Date validFrom,
			Date validTo, Set<CaseInfo> caseInfos) {
		this.number = number;
		this.organizationsByAssistanceCompany = organizationsByAssistanceCompany;
		this.organizationsByInsuaranceCompany = organizationsByInsuaranceCompany;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.caseInfos = caseInfos;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Organizations getOrganizationsByAssistanceCompany() {
		return this.organizationsByAssistanceCompany;
	}

	public void setOrganizationsByAssistanceCompany(
			Organizations organizationsByAssistanceCompany) {
		this.organizationsByAssistanceCompany = organizationsByAssistanceCompany;
	}

	public Organizations getOrganizationsByInsuaranceCompany() {
		return this.organizationsByInsuaranceCompany;
	}

	public void setOrganizationsByInsuaranceCompany(
			Organizations organizationsByInsuaranceCompany) {
		this.organizationsByInsuaranceCompany = organizationsByInsuaranceCompany;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public Set<CaseInfo> getCaseInfos() {
		return this.caseInfos;
	}

	public void setCaseInfos(Set<CaseInfo> caseInfos) {
		this.caseInfos = caseInfos;
	}

}
