package database.pojo;

// Generated Apr 4, 2015 7:32:07 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Services generated by hbm2java
 */
public class Services implements java.io.Serializable {

	private int id;
	private String name;
	private String type;
	private String description;
	private Float priceDue;
	private Float priceExcess;
	private String performedBy;
	private String serviceLocation;
	private String specialist;
	private Set<CaseInfo> caseInfos = new HashSet<CaseInfo>(0);

	public Services() {
	}

	public Services(int id, String name, String type) {
		this.id = id;
		this.name = name;
		this.type = type;
	}

	public Services(int id, String name, String type, String description,
			Float priceDue, Float priceExcess, String performedBy,
			String serviceLocation, String specialist, Set<CaseInfo> caseInfos) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.description = description;
		this.priceDue = priceDue;
		this.priceExcess = priceExcess;
		this.performedBy = performedBy;
		this.serviceLocation = serviceLocation;
		this.specialist = specialist;
		this.caseInfos = caseInfos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getPriceDue() {
		return this.priceDue;
	}

	public void setPriceDue(Float priceDue) {
		this.priceDue = priceDue;
	}

	public Float getPriceExcess() {
		return this.priceExcess;
	}

	public void setPriceExcess(Float priceExcess) {
		this.priceExcess = priceExcess;
	}

	public String getPerformedBy() {
		return this.performedBy;
	}

	public void setPerformedBy(String performedBy) {
		this.performedBy = performedBy;
	}

	public String getServiceLocation() {
		return this.serviceLocation;
	}

	public void setServiceLocation(String serviceLocation) {
		this.serviceLocation = serviceLocation;
	}

	public String getSpecialist() {
		return this.specialist;
	}

	public void setSpecialist(String specialist) {
		this.specialist = specialist;
	}

	public Set<CaseInfo> getCaseInfos() {
		return this.caseInfos;
	}

	public void setCaseInfos(Set<CaseInfo> caseInfos) {
		this.caseInfos = caseInfos;
	}

}
