package database.pojo;

// Generated May 23, 2015 12:50:22 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TouristVisit generated by hbm2java
 */
public class TouristVisit implements java.io.Serializable {

	private Integer id;
	private Persons persons;
	private Date startDate;
	private Date endDate;
	private String resort;
	private String hotel;
	private String room;
	private String phoneNumber;
	private String address;

	public TouristVisit() {
	}

	public TouristVisit(Persons persons, String resort) {
		this.persons = persons;
		this.resort = resort;
	}

	public TouristVisit(Persons persons, Date startDate, Date endDate,
			String resort, String hotel, String room, String phoneNumber,
			String address) {
		this.persons = persons;
		this.startDate = startDate;
		this.endDate = endDate;
		this.resort = resort;
		this.hotel = hotel;
		this.room = room;
		this.phoneNumber = phoneNumber;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getResort() {
		return this.resort;
	}

	public void setResort(String resort) {
		this.resort = resort;
	}

	public String getHotel() {
		return this.hotel;
	}

	public void setHotel(String hotel) {
		this.hotel = hotel;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
