package database.pojo;

// Generated Apr 4, 2015 7:32:07 PM by Hibernate Tools 4.0.0

/**
 * Treatments generated by hbm2java
 */
public class Treatments implements java.io.Serializable {

	private Integer id;
	private Enumerations enumerations;
	private String name;
	private String description;
	private Float price;

	public Treatments() {
	}

	public Treatments(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Treatments(Enumerations enumerations, String name,
			String description, Float price) {
		this.enumerations = enumerations;
		this.name = name;
		this.description = description;
		this.price = price;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Enumerations getEnumerations() {
		return this.enumerations;
	}

	public void setEnumerations(Enumerations enumerations) {
		this.enumerations = enumerations;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

}
