package database.pojo;

// Generated Apr 30, 2015 6:48:37 PM by Hibernate Tools 4.0.0

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private Persons persons;
	private String username;
	private String password;
	private String active;
	private String userRole;

	public Users() {
	}

	public Users(Persons persons, String username, String password,
			String active, String userRole) {
		this.persons = persons;
		this.username = username;
		this.password = password;
		this.active = active;
		this.userRole = userRole;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

}
