package pojo.classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CaseInfo generated by hbm2java
 */
public class CaseInfo implements java.io.Serializable {

	private Integer id;
	private Treatments treatments;
	private CaseInfo caseInfo;
	private Persons persons;
	private Medicaments medicaments;
	private Set medicalCaseses = new HashSet(0);
	private Set caseInfos = new HashSet(0);
	private Set documentations = new HashSet(0);

	public CaseInfo() {
	}

	public CaseInfo(Persons persons) {
		this.persons = persons;
	}

	public CaseInfo(Treatments treatments, CaseInfo caseInfo, Persons persons,
			Medicaments medicaments, Set medicalCaseses, Set caseInfos,
			Set documentations) {
		this.treatments = treatments;
		this.caseInfo = caseInfo;
		this.persons = persons;
		this.medicaments = medicaments;
		this.medicalCaseses = medicalCaseses;
		this.caseInfos = caseInfos;
		this.documentations = documentations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Treatments getTreatments() {
		return this.treatments;
	}

	public void setTreatments(Treatments treatments) {
		this.treatments = treatments;
	}

	public CaseInfo getCaseInfo() {
		return this.caseInfo;
	}

	public void setCaseInfo(CaseInfo caseInfo) {
		this.caseInfo = caseInfo;
	}

	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	public Medicaments getMedicaments() {
		return this.medicaments;
	}

	public void setMedicaments(Medicaments medicaments) {
		this.medicaments = medicaments;
	}

	public Set getMedicalCaseses() {
		return this.medicalCaseses;
	}

	public void setMedicalCaseses(Set medicalCaseses) {
		this.medicalCaseses = medicalCaseses;
	}

	public Set getCaseInfos() {
		return this.caseInfos;
	}

	public void setCaseInfos(Set caseInfos) {
		this.caseInfos = caseInfos;
	}

	public Set getDocumentations() {
		return this.documentations;
	}

	public void setDocumentations(Set documentations) {
		this.documentations = documentations;
	}

}
