package pojo.classes;

// Generated Apr 29, 2015 9:23:50 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EnumerationTypes generated by hbm2java
 */
public class EnumerationTypes implements java.io.Serializable {

	private String type;
	private String description;
	private Set<Enumerations> enumerationses = new HashSet<Enumerations>(0);

	public EnumerationTypes() {
	}

	public EnumerationTypes(String type) {
		this.type = type;
	}

	public EnumerationTypes(String type, String description,
			Set<Enumerations> enumerationses) {
		this.type = type;
		this.description = description;
		this.enumerationses = enumerationses;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Enumerations> getEnumerationses() {
		return this.enumerationses;
	}

	public void setEnumerationses(Set<Enumerations> enumerationses) {
		this.enumerationses = enumerationses;
	}

}
