package pojo.classes;

// Generated Apr 29, 2015 9:23:50 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MedicalReport generated by hbm2java
 */
public class MedicalReport implements java.io.Serializable {

	private Integer id;
	private String complaints;
	private String alcDrugs;
	private String acceptTreatment;
	private String presentCondition;
	private String therapy;
	private String recommendation;
	private Date medicalCaseDate;
	private Set<CaseInfo> caseInfos = new HashSet<CaseInfo>(0);
	private Set<Diagnosis> diagnosises = new HashSet<Diagnosis>(0);

	public MedicalReport() {
	}

	public MedicalReport(String complaints, String alcDrugs,
			String acceptTreatment, String presentCondition, String therapy,
			String recommendation, Date medicalCaseDate,
			Set<CaseInfo> caseInfos, Set<Diagnosis> diagnosises) {
		this.complaints = complaints;
		this.alcDrugs = alcDrugs;
		this.acceptTreatment = acceptTreatment;
		this.presentCondition = presentCondition;
		this.therapy = therapy;
		this.recommendation = recommendation;
		this.medicalCaseDate = medicalCaseDate;
		this.caseInfos = caseInfos;
		this.diagnosises = diagnosises;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getComplaints() {
		return this.complaints;
	}

	public void setComplaints(String complaints) {
		this.complaints = complaints;
	}

	public String getAlcDrugs() {
		return this.alcDrugs;
	}

	public void setAlcDrugs(String alcDrugs) {
		this.alcDrugs = alcDrugs;
	}

	public String getAcceptTreatment() {
		return this.acceptTreatment;
	}

	public void setAcceptTreatment(String acceptTreatment) {
		this.acceptTreatment = acceptTreatment;
	}

	public String getPresentCondition() {
		return this.presentCondition;
	}

	public void setPresentCondition(String presentCondition) {
		this.presentCondition = presentCondition;
	}

	public String getTherapy() {
		return this.therapy;
	}

	public void setTherapy(String therapy) {
		this.therapy = therapy;
	}

	public String getRecommendation() {
		return this.recommendation;
	}

	public void setRecommendation(String recommendation) {
		this.recommendation = recommendation;
	}

	public Date getMedicalCaseDate() {
		return this.medicalCaseDate;
	}

	public void setMedicalCaseDate(Date medicalCaseDate) {
		this.medicalCaseDate = medicalCaseDate;
	}

	public Set<CaseInfo> getCaseInfos() {
		return this.caseInfos;
	}

	public void setCaseInfos(Set<CaseInfo> caseInfos) {
		this.caseInfos = caseInfos;
	}

	public Set<Diagnosis> getDiagnosises() {
		return this.diagnosises;
	}

	public void setDiagnosises(Set<Diagnosis> diagnosises) {
		this.diagnosises = diagnosises;
	}

}
