package pojo.classes;

// Generated Apr 4, 2015 7:32:07 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persons generated by hbm2java
 */
public class Persons implements java.io.Serializable {

	private String socialNumber;
	private Enumerations enumerationsByJobTitle;
	private Enumerations enumerationsByTitle;
	private Enumerations enumerationsByRole;
	private Enumerations enumerationsBySex;
	private String firstName;
	private String middleName;
	private String lastName;
	private Date birthDate;
	private Set<Organizations> organizationses = new HashSet<Organizations>(0);
	private Set<Contacts> contactses = new HashSet<Contacts>(0);
	private Set<CaseInfo> caseInfos = new HashSet<CaseInfo>(0);
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<TouristVisit> touristVisits = new HashSet<TouristVisit>(0);

	public Persons() {
	}

	public Persons(String socialNumber, Enumerations enumerationsByJobTitle,
			Enumerations enumerationsByTitle, Enumerations enumerationsByRole,
			Enumerations enumerationsBySex, String firstName, String lastName,
			Date birthDate) {
		this.socialNumber = socialNumber;
		this.enumerationsByJobTitle = enumerationsByJobTitle;
		this.enumerationsByTitle = enumerationsByTitle;
		this.enumerationsByRole = enumerationsByRole;
		this.enumerationsBySex = enumerationsBySex;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDate = birthDate;
	}

	public Persons(String socialNumber, Enumerations enumerationsByJobTitle,
			Enumerations enumerationsByTitle, Enumerations enumerationsByRole,
			Enumerations enumerationsBySex, String firstName,
			String middleName, String lastName, Date birthDate,
			Set<Organizations> organizationses, Set<Contacts> contactses,
			Set<CaseInfo> caseInfos, Set<Users> userses,
			Set<TouristVisit> touristVisits) {
		this.socialNumber = socialNumber;
		this.enumerationsByJobTitle = enumerationsByJobTitle;
		this.enumerationsByTitle = enumerationsByTitle;
		this.enumerationsByRole = enumerationsByRole;
		this.enumerationsBySex = enumerationsBySex;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.birthDate = birthDate;
		this.organizationses = organizationses;
		this.contactses = contactses;
		this.caseInfos = caseInfos;
		this.userses = userses;
		this.touristVisits = touristVisits;
	}

	public String getSocialNumber() {
		return this.socialNumber;
	}

	public void setSocialNumber(String socialNumber) {
		this.socialNumber = socialNumber;
	}

	public Enumerations getEnumerationsByJobTitle() {
		return this.enumerationsByJobTitle;
	}

	public void setEnumerationsByJobTitle(Enumerations enumerationsByJobTitle) {
		this.enumerationsByJobTitle = enumerationsByJobTitle;
	}

	public Enumerations getEnumerationsByTitle() {
		return this.enumerationsByTitle;
	}

	public void setEnumerationsByTitle(Enumerations enumerationsByTitle) {
		this.enumerationsByTitle = enumerationsByTitle;
	}

	public Enumerations getEnumerationsByRole() {
		return this.enumerationsByRole;
	}

	public void setEnumerationsByRole(Enumerations enumerationsByRole) {
		this.enumerationsByRole = enumerationsByRole;
	}

	public Enumerations getEnumerationsBySex() {
		return this.enumerationsBySex;
	}

	public void setEnumerationsBySex(Enumerations enumerationsBySex) {
		this.enumerationsBySex = enumerationsBySex;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Set<Organizations> getOrganizationses() {
		return this.organizationses;
	}

	public void setOrganizationses(Set<Organizations> organizationses) {
		this.organizationses = organizationses;
	}

	public Set<Contacts> getContactses() {
		return this.contactses;
	}

	public void setContactses(Set<Contacts> contactses) {
		this.contactses = contactses;
	}

	public Set<CaseInfo> getCaseInfos() {
		return this.caseInfos;
	}

	public void setCaseInfos(Set<CaseInfo> caseInfos) {
		this.caseInfos = caseInfos;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	public Set<TouristVisit> getTouristVisits() {
		return this.touristVisits;
	}

	public void setTouristVisits(Set<TouristVisit> touristVisits) {
		this.touristVisits = touristVisits;
	}

}
