package pojo.classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

/**
 * PersonContactLink generated by hbm2java
 */
public class PersonContactLink implements java.io.Serializable {

	private Integer id;
	private Persons persons;
	private Contacts contacts;

	public PersonContactLink() {
	}

	public PersonContactLink(Persons persons, Contacts contacts) {
		this.persons = persons;
		this.contacts = contacts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

}
