package pojo.classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TouristVisit generated by hbm2java
 */
public class TouristVisit implements java.io.Serializable {

	private Integer id;
	private Persons persons;
	private Date from;
	private Date to;
	private String resort;
	private String hotel;
	private String room;
	private String contactNumber; 

	public TouristVisit() {
	}

	public TouristVisit(Persons persons, Date from, Date to, String resort,
			String hotel, String room,String contactNumber) {
		this.persons = persons;
		this.from = from;
		this.to = to;
		this.resort = resort;
		this.hotel = hotel;
		this.room = room;
		this.contactNumber=contactNumber;
	}

	public TouristVisit(TouristVisit touristVisit) {
		this.persons = touristVisit.getPersons();
		this.from = touristVisit.getFrom();
		this.to = touristVisit.getTo();
		this.resort = touristVisit.getResort();
		this.hotel = touristVisit.getHotel();
		this.room = touristVisit.getRoom();
		this.contactNumber=touristVisit.contactNumber;
	}	

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	public Date getFrom() {
		return this.from;
	}

	public void setFrom(Date from) {
		this.from = from;
	}

	public Date getTo() {
		return this.to;
	}

	public void setTo(Date to) {
		this.to = to;
	}

	public String getResort() {
		return this.resort;
	}

	public void setResort(String resort) {
		this.resort = resort;
	}

	public String getHotel() {
		return this.hotel;
	}

	public void setHotel(String hotel) {
		this.hotel = hotel;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

}
