package pojo.classes;

// Generated Apr 29, 2015 9:23:50 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TouristVisit generated by hbm2java
 */
public class TouristVisit implements java.io.Serializable {

	private Integer id;
	private Persons persons;
	private Date from;
	private Date to;
	private String resort;
	private String hotel;
	private String room;
	private String phoneNumber;
	private String address;

	public TouristVisit() {
	}

	public TouristVisit(Persons persons, String resort) {
		this.persons = persons;
		this.resort = resort;
	}

	public TouristVisit(Persons persons, Date from, Date to, String resort,
			String hotel, String room, String phoneNumber, String address) {
		this.persons = persons;
		this.from = from;
		this.to = to;
		this.resort = resort;
		this.hotel = hotel;
		this.room = room;
		this.phoneNumber = phoneNumber;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	public Date getFrom() {
		return this.from;
	}

	public void setFrom(Date from) {
		this.from = from;
	}

	public Date getTo() {
		return this.to;
	}

	public void setTo(Date to) {
		this.to = to;
	}

	public String getResort() {
		return this.resort;
	}

	public void setResort(String resort) {
		this.resort = resort;
	}

	public String getHotel() {
		return this.hotel;
	}

	public void setHotel(String hotel) {
		this.hotel = hotel;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
