package pojo.classes;

// Generated May 18, 2014 7:33:38 PM by Hibernate Tools 4.0.0

/**
 * TreatmentMedicamentLink generated by hbm2java
 */
public class TreatmentMedicamentLink implements java.io.Serializable {

	private Integer id;
	private Medicaments medicaments;
	private Treatments treatments;

	public TreatmentMedicamentLink() {
	}

	public TreatmentMedicamentLink(Medicaments medicaments,
			Treatments treatments) {
		this.medicaments = medicaments;
		this.treatments = treatments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Medicaments getMedicaments() {
		return this.medicaments;
	}

	public void setMedicaments(Medicaments medicaments) {
		this.medicaments = medicaments;
	}

	public Treatments getTreatments() {
		return this.treatments;
	}

	public void setTreatments(Treatments treatments) {
		this.treatments = treatments;
	}

}
