package beans;

import javax.persistence.Column;

import com.sun.istack.internal.NotNull;

import annotations.MyEdit;
import annotations.MyTable;

/**
 * Treatments generated by hbm2java
 */
@MyTable(caption = "Treatments", popupCaption = "Treatments", height = 300)
public class TreatmentBean {

	@NotNull
	@Column(name = "name", nullable = false, length = 45)
	@MyEdit(caption = "Name")
	private String name;

	@NotNull
	@Column(name = "description", nullable = false, length = 45)
	@MyEdit(caption = "Description")
	private String description;

	@NotNull
	@Column(name = "price", nullable = false)
	@MyEdit(caption = "Price")
	private Double price;

	public TreatmentBean() {
	}

	public TreatmentBean(String name, String description, Double price) {
		this.name = name;
		this.description = description;
		this.price = price;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}

