package web.forms;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;


import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.AbstractComponent;
import com.vaadin.ui.AbstractSelect;
import com.vaadin.ui.AbstractSelect.NewItemHandler;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

import database.dao.DaoIntrfc;
import database.pojo.Enumerations;
import database.pojo.Organizations;
import database.pojo.Persons;
import database.pojo.TouristVisit;

import web.StepIntrfc;
import web.classes.ComponentValidator;
import web.classes.PropertyManager;
import web.views.AbstractView;

public class PersonTouristVisitForm extends Form implements StepIntrfc {

	private static final long serialVersionUID = 1L;
	private FormLayout formLayout;
	private PopupDateField popupDateFieldStart;
	private PopupDateField popupDateFieldEnd;
	private TextField textFieldAddress;
	private ComboBox comboBoxResort;
	private ComboBox comboBoxHotel;
	private TextField textFieldRoomNumber;
	private TextField textFieldContactNumber;
	private Label labelDivideDates;

	public PersonTouristVisitForm() {

		buildMainLayout();
		setCompositionRoot(formLayout);

	}

	public PersonTouristVisitForm(AbstractView view, String label) {
		super(view, label, new FormLayout());
		setCompositionRoot(getLayout());
	}

	public Layout viewLayout(String mode){
		return buildLayout(mode);
	}

	public Layout buildLayout(String mode) {	

		//get component validator
		ComponentValidator componentValidator = getComponentValidator();
		//get propertyManager
		final PropertyManager propertyManager = getPropertyManager();
		//get access to DB
		final DaoIntrfc dao = getDao();

		//build main layout
		Layout formLayout = buildMainLayout();
		setLayout(formLayout);

		//set captions
		popupDateFieldStart.setCaption(propertyManager.getLabelDtl("Vacation period")+": ");
		popupDateFieldEnd.setCaption(propertyManager.getLabelDtl("to date: "));
		textFieldAddress.setCaption(propertyManager.getLabelDtl("address")+": ");
		comboBoxResort.setCaption(propertyManager.getLabelDtl("Resort")+": ");
		comboBoxHotel.setCaption(propertyManager.getLabelDtl("Hotel")+": ");
		textFieldRoomNumber.setCaption(propertyManager.getLabelDtl("Room number")+": ");
		textFieldContactNumber.setCaption(propertyManager.getLabelDtl("Phone number")+": ");

		//get object that will be bind to the web.components.table.generated.components
		final TouristVisit touristVisit;
		//mode.equals("update") || 
		if(getData() != null){
			touristVisit = (TouristVisit)getData();
		}else{
			//set initial values
			touristVisit = new TouristVisit();
			touristVisit.setStartDate(new Date());
			touristVisit.setEndDate(new Date());
			touristVisit.setHotel("");
			touristVisit.setPersons(new Persons());
			touristVisit.setResort("");
			touristVisit.setRoom("");	
			touristVisit.setPhoneNumber("");
			touristVisit.setAddress("");
			setData(touristVisit);
		}

		// Custom handling for new items
		comboBoxHotel.setNewItemHandler(new NewItemHandler() {
			private static final long serialVersionUID = 1L;

			@Override
			public void addNewItem(String newItemCaption) {
				if (!newItemCaption.equals(""))
				{
					comboBoxHotel.addItem(newItemCaption);
					// Remember to set the selection to the new item
					comboBoxHotel.select(newItemCaption);
					Notification.show(propertyManager.getLabelDtl("Added new Hotel")+" " +newItemCaption);
				}
			}
		});
		comboBoxResort.setNewItemHandler(new NewItemHandler() {
			private static final long serialVersionUID = 1L;

			@Override
			public void addNewItem(String newItemCaption) {
				if (!newItemCaption.equals(""))
				{
					comboBoxResort.addItem(newItemCaption);
					// Remember to set the selection to the new item
					comboBoxResort.select(newItemCaption);
					Notification.show(propertyManager.getLabelDtl("Added new Resort")+" " +newItemCaption);
				}
			}
		});

		//add listeners
		popupDateFieldStart.addValueChangeListener(
				new Property.ValueChangeListener() {
					private static final long serialVersionUID = 1L;
					public void valueChange(ValueChangeEvent event) {
						Object value=popupDateFieldStart.getValue();
						if (value != null){
						touristVisit.setStartDate((Date)event.getProperty().getValue());
						popupDateFieldStart.setData((Date)event.getProperty().getValue());
						popupDateFieldStart.setComponentError(null);
						}
					}
				});

		popupDateFieldEnd.addValueChangeListener(
				new Property.ValueChangeListener() {
					private static final long serialVersionUID = 1L;
					public void valueChange(ValueChangeEvent event) {
						Object value=popupDateFieldEnd.getValue();
						if (value != null){
						touristVisit.setEndDate((Date) value);
						popupDateFieldEnd.setData((Date)event.getProperty().getValue());
						popupDateFieldEnd.setComponentError(null);
						}
					}
				});

		comboBoxResort.addValueChangeListener(
				new Property.ValueChangeListener() {
					private static final long serialVersionUID = 1L;
					public void valueChange(ValueChangeEvent event) {
						Object value=comboBoxResort.getValue();
						if (value != null){
							touristVisit.setResort(event.getProperty().getValue().toString());
							comboBoxResort.setData(event.getProperty().getValue().toString());
							comboBoxResort.setComponentError(null);
						}
					}
				});

		comboBoxHotel.addValueChangeListener(
				new Property.ValueChangeListener() {
					private static final long serialVersionUID = 1L;
					public void valueChange(ValueChangeEvent event) {	
						Object value=comboBoxHotel.getValue();								
						if (value != null){
							touristVisit.setHotel(event.getProperty().getValue().toString());
							comboBoxHotel.setData(event.getProperty().getValue().toString());
							comboBoxHotel.setComponentError(null);
						}
					}
				});

		textFieldRoomNumber.addValueChangeListener(
				new Property.ValueChangeListener() {
					private static final long serialVersionUID = 1L;
					public void valueChange(ValueChangeEvent event) {
						touristVisit.setRoom(event.getProperty().getValue().toString());
						textFieldRoomNumber.setData(event.getProperty().getValue().toString());
						textFieldRoomNumber.setComponentError(null);
					}
				});

		textFieldContactNumber.addValueChangeListener(
				new Property.ValueChangeListener() {
					private static final long serialVersionUID = 1L;
					public void valueChange(ValueChangeEvent event) {
						touristVisit.setPhoneNumber(event.getProperty().getValue().toString());
						textFieldContactNumber.setData(event.getProperty().getValue().toString());
						textFieldContactNumber.setComponentError(null);
					}
				});

		textFieldAddress.addValueChangeListener(
				new Property.ValueChangeListener() {
					private static final long serialVersionUID = 1L;
					public void valueChange(ValueChangeEvent event) {
						touristVisit.setAddress(event.getProperty().getValue().toString());
						textFieldAddress.setData(event.getProperty().getValue().toString());
						textFieldAddress.setComponentError(null);
					}
				});

		//retrieve and bind data to fields
		//mode.equals("update") ||
		if( getData() != null){
			popupDateFieldStart.setValue(touristVisit.getStartDate());
			popupDateFieldEnd.setValue(touristVisit.getEndDate());

			textFieldAddress.setValue(touristVisit.getAddress());

			comboBoxResort.addItem(touristVisit.getResort());
			comboBoxResort.select(touristVisit.getResort());

			comboBoxHotel.addItem(touristVisit.getHotel());
			comboBoxHotel.select(touristVisit.getHotel());

			textFieldRoomNumber.setValue(touristVisit.getRoom());
			textFieldContactNumber.setValue(touristVisit.getPhoneNumber());
		}else{
			//default values
			popupDateFieldStart.setValue(new Date());
			popupDateFieldEnd.setValue(new Date());
		}

		//manage mode of the form
		if(!mode.equals("validation")){
			setCompositionRoot(formLayout);
		}else{
			setEnabled(false);
		}

		return formLayout;
	}

	@AutoGenerated
	public Layout buildMainLayout() {

		// common part: create layout
		formLayout = new FormLayout();
		formLayout.setImmediate(true);

		// popupDateFieldStart
		popupDateFieldStart = new PopupDateField();
		popupDateFieldStart.setImmediate(true);
		popupDateFieldStart.setWidth("110px");
		popupDateFieldStart.setHeight("23px");
		popupDateFieldStart.setRequired(false);
		formLayout.addComponent(popupDateFieldStart);

		// label_5
		labelDivideDates = new Label();
		labelDivideDates.setImmediate(true);
		labelDivideDates.setWidth("-1px");
		labelDivideDates.setHeight("-1px");
		labelDivideDates.setValue(" - ");
		formLayout.addComponent(labelDivideDates);

		// popupDateFieldEnd
		popupDateFieldEnd = new PopupDateField();
		popupDateFieldEnd.setImmediate(true);
		popupDateFieldEnd.setWidth("110px");
		popupDateFieldEnd.setHeight("-1px");
		popupDateFieldEnd.setRequired(false);
		formLayout.addComponent(popupDateFieldEnd);

		// textFieldAddress
		textFieldAddress = new TextField();
		textFieldAddress.setImmediate(true);
		textFieldAddress.setWidth("280px");
		textFieldAddress.setHeight("-1px");
		formLayout.addComponent(textFieldAddress);

		// comboBoxResort
		comboBoxResort = new ComboBox();
		comboBoxResort.setImmediate(true);
		comboBoxResort.setWidth("280px");
		comboBoxResort.setHeight("-1px");
		comboBoxResort.setRequired(true);
		comboBoxResort.setNewItemsAllowed(true);
		comboBoxResort.setNullSelectionAllowed(true);
		comboBoxResort.setNullSelectionItemId("");
		formLayout.addComponent(comboBoxResort);

		// comboBoxHotel
		comboBoxHotel = new ComboBox();
		comboBoxHotel.setImmediate(true);
		comboBoxHotel.setWidth("280px");
		comboBoxHotel.setHeight("-1px");
		comboBoxHotel.setNewItemsAllowed(true);
		comboBoxHotel.setNullSelectionAllowed(true);
		comboBoxHotel.setNullSelectionItemId("");
		formLayout.addComponent(comboBoxHotel);

		// textFieldRoomNumber
		textFieldRoomNumber = new TextField();
		textFieldRoomNumber.setImmediate(true);
		textFieldRoomNumber.setWidth("90px");
		textFieldRoomNumber.setHeight("-1px");
		formLayout.addComponent(textFieldRoomNumber);

		// textFieldContactNumber
		textFieldContactNumber = new TextField();
		textFieldContactNumber.setImmediate(true);
		textFieldContactNumber.setWidth("150px");
		textFieldContactNumber.setHeight("-1px");
		formLayout.addComponent(textFieldContactNumber);

		return formLayout;
	}

	public List<String> getOrganizationNameList(DaoIntrfc dao,String typeOrganization){
		Map<Enumerations, String> typeOrg = dao.getEnumeration("organization");
		Enumerations orgEnum=new Enumerations();

		for (Map.Entry<Enumerations, String> entry : typeOrg.entrySet()) {
			Enumerations enumeration = entry.getKey();			
			String label = entry.getValue();
			if (label.equalsIgnoreCase(typeOrganization)){
				orgEnum=enumeration;
				break;
			}
		} 

		Organizations hotels=new Organizations();
		hotels.setEnumerations(orgEnum);

		List<Object> orgs=dao.findByExample(hotels);

		List<String> hotelList=new ArrayList<String>();

		for (Object organization:orgs){
			Organizations org=(Organizations) organization;
			hotelList.add(org.getName());
			//System.out.println(org.getName());
		}		

		return hotelList;
	}

	@Override
	public boolean process(HashMap<String, Form> steps) {
		//get access to DB
		DaoIntrfc dao = getDao();

		TouristVisit touristVisit = (TouristVisit) getData();

		Persons person=(Persons) steps.get("stepCreatePerson").getData();
		touristVisit.setPersons(person);

		dao.evict(touristVisit);

		steps.get("stepTouristVisit").setData(touristVisit);

		return true;
	}

}
